# Generated by Django 4.1.5 on 2023-02-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_senha_cliente_password_cliente_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_login',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
