# Generated by Django 4.1.5 on 2023-02-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_senha_alter_cliente_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
    ]
