# Generated by Django 4.1.5 on 2023-02-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_cliente_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
