# Generated by Django 4.1.5 on 2023-02-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='dono',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
