# Generated by Django 4.1.5 on 2023-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=15)),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=5)),
                ('foto1', models.CharField(max_length=100)),
                ('foto2', models.CharField(max_length=100)),
            ],
        ),
    ]
