# Generated by Django 4.1.5 on 2023-02-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpatas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='avaliacao',
            field=models.CharField(max_length=1),
        ),
    ]
