# Generated by Django 4.1.5 on 2023-02-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpatas', '0002_alter_servicos_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='avaliacao',
            field=models.IntegerField(max_length=1),
        ),
    ]
