# Generated by Django 4.1.5 on 2023-02-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpatas', '0003_alter_servicos_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
