# Generated by Django 4.1.5 on 2023-02-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpatas', '0005_alter_servicos_foto1_alter_servicos_foto2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='nome',
            new_name='nome_servico',
        ),
        migrations.AlterField(
            model_name='servicos',
            name='avaliacao',
            field=models.IntegerField(),
        ),
    ]
